Default Avatar selection.
amueller-89/RockPaperAgents pull request #1
Opened 2021-04-22 09:42 UTC by IvanSpirandelli

# Default Avatar Selection

**The process is working in general. To test it out:**
* Click on account
* Click avatar of your choice
* Reload

**Stuff that is Left to do: **
* The buttons for selecting the avatars should look nicer.
* Is there a way to update the message part of the page/ the shown avatars without reloading?
* Where do we want to save the information of what is a default avatar? DB? Right now it is just a list passed from the endpoint "/change_avatar/"

Still pretty hapopy with my progress.

2021-04-22 10:45 UTC, amueller-89 requested changes
da guckste aber nochma drueber wa.
pff also leute schickt das arbeitsamt...

2021-04-22 10:45 UTC, amueller-89 commented on main.py
> +@app.post("/change_avatar/")
should be of type "get"

2021-04-22 10:45 UTC, amueller-89 commented on templates/SPA-loginbar.html
> +
naja ok

2021-04-22 10:45 UTC, amueller-89 commented on templates/SPA-loginbar.html
> -    <div class="header">Login failed</div>
unintended changes??? please fix

2021-04-22 10:45 UTC, amueller-89 commented on templates/SPA-loginbar.html
> +    <style>
collect stylings somewhere nice in future refactoring?

2021-04-22 10:45 UTC, amueller-89 commented on templates/SPA-loginbar.html
> +            type: "POST",
GET!!! brudi

2021-04-23 15:12 UTC, IvanSpirandelli reviewed
I like it

2021-04-25 15:15 UTC, merged